---
## Default Elasticsearch configuration from Elasticsearch base image.
## https://github.com/elastic/elasticsearch/blob/main/distribution/docker/src/docker/config/elasticsearch.yml
#
cluster.name: docker-cluster
network.host: 0.0.0.0

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
#
xpack.license.self_generated.type: trial
xpack.security.enabled: true

analysis:
  filter:
    synonym_filter:
      type: synonym
      synonyms_path: dictionary/synonym.txt
    stop_filter:
      type: stop
      stopwords_path: dictionary/stopword.txt
  tokenizer:
    nori_tokenizer:
      type: nori
      user_dictionary: dictionary/userdict_ko.txt
      discard_punctuation: true
